package cn.ct.community.model;

import java.util.ArrayList;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("PARENT_ID is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("PARENT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("PARENT_ID =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("PARENT_ID <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("PARENT_ID >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("PARENT_ID >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("PARENT_ID <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("PARENT_ID <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("PARENT_ID in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("PARENT_ID not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("PARENT_ID between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("PARENT_ID not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorIsNull() {
            addCriterion("COMMENT_CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorIsNotNull() {
            addCriterion("COMMENT_CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorEqualTo(Integer value) {
            addCriterion("COMMENT_CREATOR =", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorNotEqualTo(Integer value) {
            addCriterion("COMMENT_CREATOR <>", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorGreaterThan(Integer value) {
            addCriterion("COMMENT_CREATOR >", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_CREATOR >=", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorLessThan(Integer value) {
            addCriterion("COMMENT_CREATOR <", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_CREATOR <=", value, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorIn(List<Integer> values) {
            addCriterion("COMMENT_CREATOR in", values, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorNotIn(List<Integer> values) {
            addCriterion("COMMENT_CREATOR not in", values, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_CREATOR between", value1, value2, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andCommentCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_CREATOR not between", value1, value2, "commentCreator");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIsNull() {
            addCriterion("GTM_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIsNotNull() {
            addCriterion("GTM_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGtmCreateEqualTo(Long value) {
            addCriterion("GTM_CREATE =", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotEqualTo(Long value) {
            addCriterion("GTM_CREATE <>", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateGreaterThan(Long value) {
            addCriterion("GTM_CREATE >", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("GTM_CREATE >=", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateLessThan(Long value) {
            addCriterion("GTM_CREATE <", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateLessThanOrEqualTo(Long value) {
            addCriterion("GTM_CREATE <=", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIn(List<Long> values) {
            addCriterion("GTM_CREATE in", values, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotIn(List<Long> values) {
            addCriterion("GTM_CREATE not in", values, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateBetween(Long value1, Long value2) {
            addCriterion("GTM_CREATE between", value1, value2, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotBetween(Long value1, Long value2) {
            addCriterion("GTM_CREATE not between", value1, value2, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIsNull() {
            addCriterion("GTM_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIsNotNull() {
            addCriterion("GTM_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateEqualTo(Long value) {
            addCriterion("GTM_UPDATE =", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotEqualTo(Long value) {
            addCriterion("GTM_UPDATE <>", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateGreaterThan(Long value) {
            addCriterion("GTM_UPDATE >", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateGreaterThanOrEqualTo(Long value) {
            addCriterion("GTM_UPDATE >=", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateLessThan(Long value) {
            addCriterion("GTM_UPDATE <", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateLessThanOrEqualTo(Long value) {
            addCriterion("GTM_UPDATE <=", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIn(List<Long> values) {
            addCriterion("GTM_UPDATE in", values, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotIn(List<Long> values) {
            addCriterion("GTM_UPDATE not in", values, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateBetween(Long value1, Long value2) {
            addCriterion("GTM_UPDATE between", value1, value2, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotBetween(Long value1, Long value2) {
            addCriterion("GTM_UPDATE not between", value1, value2, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIsNull() {
            addCriterion("LIKE_COUNTS is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIsNotNull() {
            addCriterion("LIKE_COUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountsEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS =", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS <>", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsGreaterThan(Integer value) {
            addCriterion("LIKE_COUNTS >", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS >=", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsLessThan(Integer value) {
            addCriterion("LIKE_COUNTS <", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsLessThanOrEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS <=", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIn(List<Integer> values) {
            addCriterion("LIKE_COUNTS in", values, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotIn(List<Integer> values) {
            addCriterion("LIKE_COUNTS not in", values, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsBetween(Integer value1, Integer value2) {
            addCriterion("LIKE_COUNTS between", value1, value2, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("LIKE_COUNTS not between", value1, value2, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("CONTENT is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("CONTENT is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("CONTENT =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("CONTENT <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("CONTENT >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("CONTENT >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("CONTENT <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("CONTENT <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("CONTENT like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("CONTENT not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("CONTENT in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("CONTENT not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("CONTENT between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("CONTENT not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNull() {
            addCriterion("COMMENT_COUNTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNotNull() {
            addCriterion("COMMENT_COUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS =", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS <>", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThan(Integer value) {
            addCriterion("COMMENT_COUNTS >", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS >=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThan(Integer value) {
            addCriterion("COMMENT_COUNTS <", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS <=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIn(List<Integer> values) {
            addCriterion("COMMENT_COUNTS in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotIn(List<Integer> values) {
            addCriterion("COMMENT_COUNTS not in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_COUNTS between", value1, value2, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_COUNTS not between", value1, value2, "commentCounts");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMMENT
     *
     * @mbg.generated do_not_delete_during_merge Thu Sep 12 22:15:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table COMMENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}