package cn.ct.community.model;

public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.TYPE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.COMMENT_CREATOR
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Integer commentCreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.GTM_CREATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Long gtmCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.GTM_UPDATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Long gtmUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.LIKE_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Integer likeCounts;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.CONTENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMENT.COMMENT_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    private Integer commentCounts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.ID
     *
     * @return the value of COMMENT.ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.ID
     *
     * @param id the value for COMMENT.ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.PARENT_ID
     *
     * @return the value of COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.PARENT_ID
     *
     * @param parentId the value for COMMENT.PARENT_ID
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.TYPE
     *
     * @return the value of COMMENT.TYPE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.TYPE
     *
     * @param type the value for COMMENT.TYPE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.COMMENT_CREATOR
     *
     * @return the value of COMMENT.COMMENT_CREATOR
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Integer getCommentCreator() {
        return commentCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.COMMENT_CREATOR
     *
     * @param commentCreator the value for COMMENT.COMMENT_CREATOR
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setCommentCreator(Integer commentCreator) {
        this.commentCreator = commentCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.GTM_CREATE
     *
     * @return the value of COMMENT.GTM_CREATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Long getGtmCreate() {
        return gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.GTM_CREATE
     *
     * @param gtmCreate the value for COMMENT.GTM_CREATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setGtmCreate(Long gtmCreate) {
        this.gtmCreate = gtmCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.GTM_UPDATE
     *
     * @return the value of COMMENT.GTM_UPDATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Long getGtmUpdate() {
        return gtmUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.GTM_UPDATE
     *
     * @param gtmUpdate the value for COMMENT.GTM_UPDATE
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setGtmUpdate(Long gtmUpdate) {
        this.gtmUpdate = gtmUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.LIKE_COUNTS
     *
     * @return the value of COMMENT.LIKE_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Integer getLikeCounts() {
        return likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.LIKE_COUNTS
     *
     * @param likeCounts the value for COMMENT.LIKE_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setLikeCounts(Integer likeCounts) {
        this.likeCounts = likeCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.CONTENT
     *
     * @return the value of COMMENT.CONTENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.CONTENT
     *
     * @param content the value for COMMENT.CONTENT
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMENT.COMMENT_COUNTS
     *
     * @return the value of COMMENT.COMMENT_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public Integer getCommentCounts() {
        return commentCounts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMENT.COMMENT_COUNTS
     *
     * @param commentCounts the value for COMMENT.COMMENT_COUNTS
     *
     * @mbg.generated Thu Sep 12 22:15:35 CST 2019
     */
    public void setCommentCounts(Integer commentCounts) {
        this.commentCounts = commentCounts;
    }
}