package cn.ct.community.model;

import java.util.ArrayList;
import java.util.List;

public class QuestionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public QuestionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("TITLE is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("TITLE is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("TITLE =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("TITLE <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("TITLE >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("TITLE >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("TITLE <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("TITLE <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("TITLE like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("TITLE not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("TITLE in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("TITLE not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("TITLE between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("TITLE not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andDescrptionIsNull() {
            addCriterion("DESCRPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescrptionIsNotNull() {
            addCriterion("DESCRPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescrptionEqualTo(String value) {
            addCriterion("DESCRPTION =", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionNotEqualTo(String value) {
            addCriterion("DESCRPTION <>", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionGreaterThan(String value) {
            addCriterion("DESCRPTION >", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRPTION >=", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionLessThan(String value) {
            addCriterion("DESCRPTION <", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRPTION <=", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionLike(String value) {
            addCriterion("DESCRPTION like", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionNotLike(String value) {
            addCriterion("DESCRPTION not like", value, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionIn(List<String> values) {
            addCriterion("DESCRPTION in", values, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionNotIn(List<String> values) {
            addCriterion("DESCRPTION not in", values, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionBetween(String value1, String value2) {
            addCriterion("DESCRPTION between", value1, value2, "descrption");
            return (Criteria) this;
        }

        public Criteria andDescrptionNotBetween(String value1, String value2) {
            addCriterion("DESCRPTION not between", value1, value2, "descrption");
            return (Criteria) this;
        }

        public Criteria andTagIsNull() {
            addCriterion("TAG is null");
            return (Criteria) this;
        }

        public Criteria andTagIsNotNull() {
            addCriterion("TAG is not null");
            return (Criteria) this;
        }

        public Criteria andTagEqualTo(String value) {
            addCriterion("TAG =", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotEqualTo(String value) {
            addCriterion("TAG <>", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThan(String value) {
            addCriterion("TAG >", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagGreaterThanOrEqualTo(String value) {
            addCriterion("TAG >=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThan(String value) {
            addCriterion("TAG <", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLessThanOrEqualTo(String value) {
            addCriterion("TAG <=", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagLike(String value) {
            addCriterion("TAG like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotLike(String value) {
            addCriterion("TAG not like", value, "tag");
            return (Criteria) this;
        }

        public Criteria andTagIn(List<String> values) {
            addCriterion("TAG in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotIn(List<String> values) {
            addCriterion("TAG not in", values, "tag");
            return (Criteria) this;
        }

        public Criteria andTagBetween(String value1, String value2) {
            addCriterion("TAG between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andTagNotBetween(String value1, String value2) {
            addCriterion("TAG not between", value1, value2, "tag");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIsNull() {
            addCriterion("LIKE_COUNTS is null");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIsNotNull() {
            addCriterion("LIKE_COUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andLikeCountsEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS =", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS <>", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsGreaterThan(Integer value) {
            addCriterion("LIKE_COUNTS >", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS >=", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsLessThan(Integer value) {
            addCriterion("LIKE_COUNTS <", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsLessThanOrEqualTo(Integer value) {
            addCriterion("LIKE_COUNTS <=", value, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsIn(List<Integer> values) {
            addCriterion("LIKE_COUNTS in", values, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotIn(List<Integer> values) {
            addCriterion("LIKE_COUNTS not in", values, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsBetween(Integer value1, Integer value2) {
            addCriterion("LIKE_COUNTS between", value1, value2, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andLikeCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("LIKE_COUNTS not between", value1, value2, "likeCounts");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("CREATOR is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("CREATOR is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Integer value) {
            addCriterion("CREATOR =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Integer value) {
            addCriterion("CREATOR <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Integer value) {
            addCriterion("CREATOR >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Integer value) {
            addCriterion("CREATOR >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Integer value) {
            addCriterion("CREATOR <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Integer value) {
            addCriterion("CREATOR <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Integer> values) {
            addCriterion("CREATOR in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Integer> values) {
            addCriterion("CREATOR not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Integer value1, Integer value2) {
            addCriterion("CREATOR not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andViewCountsIsNull() {
            addCriterion("VIEW_COUNTS is null");
            return (Criteria) this;
        }

        public Criteria andViewCountsIsNotNull() {
            addCriterion("VIEW_COUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andViewCountsEqualTo(Integer value) {
            addCriterion("VIEW_COUNTS =", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsNotEqualTo(Integer value) {
            addCriterion("VIEW_COUNTS <>", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsGreaterThan(Integer value) {
            addCriterion("VIEW_COUNTS >", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("VIEW_COUNTS >=", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsLessThan(Integer value) {
            addCriterion("VIEW_COUNTS <", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsLessThanOrEqualTo(Integer value) {
            addCriterion("VIEW_COUNTS <=", value, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsIn(List<Integer> values) {
            addCriterion("VIEW_COUNTS in", values, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsNotIn(List<Integer> values) {
            addCriterion("VIEW_COUNTS not in", values, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsBetween(Integer value1, Integer value2) {
            addCriterion("VIEW_COUNTS between", value1, value2, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andViewCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("VIEW_COUNTS not between", value1, value2, "viewCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNull() {
            addCriterion("COMMENT_COUNTS is null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIsNotNull() {
            addCriterion("COMMENT_COUNTS is not null");
            return (Criteria) this;
        }

        public Criteria andCommentCountsEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS =", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS <>", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThan(Integer value) {
            addCriterion("COMMENT_COUNTS >", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsGreaterThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS >=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThan(Integer value) {
            addCriterion("COMMENT_COUNTS <", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsLessThanOrEqualTo(Integer value) {
            addCriterion("COMMENT_COUNTS <=", value, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsIn(List<Integer> values) {
            addCriterion("COMMENT_COUNTS in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotIn(List<Integer> values) {
            addCriterion("COMMENT_COUNTS not in", values, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_COUNTS between", value1, value2, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andCommentCountsNotBetween(Integer value1, Integer value2) {
            addCriterion("COMMENT_COUNTS not between", value1, value2, "commentCounts");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIsNull() {
            addCriterion("GTM_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIsNotNull() {
            addCriterion("GTM_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andGtmCreateEqualTo(Long value) {
            addCriterion("GTM_CREATE =", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotEqualTo(Long value) {
            addCriterion("GTM_CREATE <>", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateGreaterThan(Long value) {
            addCriterion("GTM_CREATE >", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateGreaterThanOrEqualTo(Long value) {
            addCriterion("GTM_CREATE >=", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateLessThan(Long value) {
            addCriterion("GTM_CREATE <", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateLessThanOrEqualTo(Long value) {
            addCriterion("GTM_CREATE <=", value, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateIn(List<Long> values) {
            addCriterion("GTM_CREATE in", values, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotIn(List<Long> values) {
            addCriterion("GTM_CREATE not in", values, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateBetween(Long value1, Long value2) {
            addCriterion("GTM_CREATE between", value1, value2, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmCreateNotBetween(Long value1, Long value2) {
            addCriterion("GTM_CREATE not between", value1, value2, "gtmCreate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIsNull() {
            addCriterion("GTM_UPDATE is null");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIsNotNull() {
            addCriterion("GTM_UPDATE is not null");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateEqualTo(Long value) {
            addCriterion("GTM_UPDATE =", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotEqualTo(Long value) {
            addCriterion("GTM_UPDATE <>", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateGreaterThan(Long value) {
            addCriterion("GTM_UPDATE >", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateGreaterThanOrEqualTo(Long value) {
            addCriterion("GTM_UPDATE >=", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateLessThan(Long value) {
            addCriterion("GTM_UPDATE <", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateLessThanOrEqualTo(Long value) {
            addCriterion("GTM_UPDATE <=", value, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateIn(List<Long> values) {
            addCriterion("GTM_UPDATE in", values, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotIn(List<Long> values) {
            addCriterion("GTM_UPDATE not in", values, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateBetween(Long value1, Long value2) {
            addCriterion("GTM_UPDATE between", value1, value2, "gtmUpdate");
            return (Criteria) this;
        }

        public Criteria andGtmUpdateNotBetween(Long value1, Long value2) {
            addCriterion("GTM_UPDATE not between", value1, value2, "gtmUpdate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 11 20:23:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table QUESTION
     *
     * @mbg.generated Wed Sep 11 20:23:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}